<a href="https://colab.research.google.com/github/AlphaKermit-999/AI-Topics-learnings/blob/main/Advanced_AI/Semantic_Search.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [8]:
df = pd.read_csv("patient_records_50k.csv")
df

patient_id             name  age  gender  \
0          P00000      Damon Moore   38    Male   
1          P00000      Damon Moore   38    Male   
2          P00000      Damon Moore   38    Male   
3          P00000      Damon Moore   38    Male   
4          P00000      Damon Moore   38    Male   
...           ...              ...  ...     ...   
196347     P35690  Michael Sampson   22    Male   
196348     P35691    Lauren Morgan   77  Female   
196349     P35691    Lauren Morgan   77  Female   
196350     P35691    Lauren Morgan   77  Female   
196351     P35691    Lauren Morgan   77  Female   

                       medical_conditions  \
0                            Hypertension   
1                            Hypertension   
2                            Hypertension   
3                            Hypertension   
4                            Hypertension   
...                                   ...   
196347                             Anemia   
196348  Asthma; Hypothyroidism; Arthritis   
196349  Asthma; Hypothyroidism; Arthritis   
196350  Asthma; Hypothyroidism; Arthritis   
196351  Asthma; Hypothyroidism; Arthritis   

                                      current_medications visit_id  \
0         Vitamin D; Lisinopril; Albuterol; Levothyroxine    V0001   
1         Vitamin D; Lisinopril; Albuterol; Levothyroxine    V0002   
2         Vitamin D; Lisinopril; Albuterol; Levothyroxine    V0003   
3         Vitamin D; Lisinopril; Albuterol; Levothyroxine    V0004   
4         Vitamin D; Lisinopril; Albuterol; Levothyroxine    V0005   
...                                                   ...      ...   
196347                                         Amlodipine    V0005   
196348  Lisinopril; Vitamin D; Albuterol; Losartan; Le...    V0001   
196349  Lisinopril; Vitamin D; Albuterol; Losartan; Le...    V0002   
196350  Lisinopril; Vitamin D; Albuterol; Losartan; Le...    V0003   
196351                         Lisinopril; Vitamin D; Alb      NaN   

        visit_date  problem_description  \
0       2024-08-13        Muscle Cramps   
1       2024-01-04              Fatigue   
2       2024-05-25           Joint Pain   
3       2024-07-01              Fatigue   
4       2024-09-26     Numbness in Feet   
...            ...                  ...   
196347  2024-07-29              Fatigue   
196348  2024-07-15             Headache   
196349  2024-06-27   Frequent Urination   
196350  2024-07-17  Shortness of Breath   
196351         NaN                  NaN   

                                             doctor_notes  \
0       Recommend tests: Lisinopril. | Encourage a Lev...   
1       Recommend tests: Albuterol. | Increase dosage ...   
2       Schedule a follow-up in Atorvastatin weeks for...   
3       Recommend tests: Albuterol. | Encourage a Lisi...   
4       Patient shows signs of Atorvastatin. Recommend...   
...                                                   ...   
196347  Recommend tests: Metformin. | Schedule a follo...   
196348  Patient shows signs of Lisinopril. Recommend 8...   
196349  Encourage a Albuterol diet and regular 8 exerc...   
196350  Encourage a Lisinopril diet and regular 9 exer...   
196351                                                NaN   

                                            tests_ordered  \
0                               Blood Pressure Monitoring   
1       Blood Pressure Monitoring; Lipid Profile; Elec...   
2                                       Electrolyte Panel   
3       Nerve Conduction Test; Lipid Profile; Electrol...   
4                        Lipid Profile; Electrolyte Panel   
...                                                   ...   
196347            Electrolyte Panel; Kidney Function Test   
196348  Blood Pressure Monitoring; HbA1c; Nerve Conduc...   
196349                                              HbA1c   
196350                                      Lipid Profile   
196351                                                NaN   

                             

In [9]:
df.columns

Index(['patient_id', 'name', 'age', 'gender', 'medical_conditions',
       'current_medications', 'visit_id', 'visit_date', 'problem_description',
       'doctor_notes', 'tests_ordered', 'test_results'],
      dtype='object')

In [10]:
df.describe(include="all")

patient_id            name            age  gender medical_conditions  \
count      196352          196352  196352.000000  196352             196352   
unique      35692           30015            NaN       2                585   
top        P35689  Jennifer Smith            NaN  Female             Anemia   
freq            6              95            NaN   98545               7510   
mean          NaN             NaN      53.898611     NaN                NaN   
std           NaN             NaN      21.027352     NaN                NaN   
min           NaN             NaN      18.000000     NaN                NaN   
25%           NaN             NaN      36.000000     NaN                NaN   
50%           NaN             NaN      54.000000     NaN                NaN   
75%           NaN             NaN      72.000000     NaN                NaN   
max           NaN             NaN      90.000000     NaN                NaN   

       current_medications visit_id  visit_date problem_description  \
count               196352   196351      196351              196351   
unique               10976        6         335                  10   
top               Losartan    V0001  2024-03-29    Numbness in Feet   
freq                  4155    35692         652               19999   
mean                   NaN      NaN         NaN                 NaN   
std                    NaN      NaN         NaN                 NaN   
min                    NaN      NaN         NaN                 NaN   
25%                    NaN      NaN         NaN                 NaN   
50%                    NaN      NaN         NaN                 NaN   
75%                    NaN      NaN         NaN                 NaN   
max                    NaN      NaN         NaN                 NaN   

                                             doctor_notes  tests_ordered  \
count                                              196351         196351   
unique                                             189941            259   
top     Recommend tests: Lisinopril. | Schedule a foll...  Lipid Profile   
freq                                                    4           9386   
mean                                                  NaN            NaN   
std                                                   NaN            NaN   
min                                                   NaN            NaN   
25%                                                   NaN            NaN   
50%                                                   NaN            NaN   
75%                                                   NaN            NaN   
max                                                   NaN            NaN   

       test_results  
count        196351  
unique       137346  
top     HbA1c: 4.03  
freq             24  
mean            NaN  
std             NaN  
min             NaN  
25%             NaN  
50%             NaN  
75%             NaN  
max             NaN

In [11]:
df = pd.read_csv("olympics.csv")

In [13]:
df.columns

Index(['Name', 'Sport', 'Country', 'Medal', 'combined'], dtype='object')

In [14]:
#df['Name']+ ' from ' + df['Country'] + " won a "+df["Medal"] + df["Sport"]
df["combined"] = df['Name']+ ' ' + df['Country'] + " "+df["Medal"] +' '+ df["Sport"]

In [15]:
df["combined"]

0     Cristiano Ronaldo China Gold Athletics
1         Usain Bolt India Bronze Gymnastics
2     Michael Phelps Russia Silver Wrestling
3      Novak Djokovic Brazil Bronze Football
4         Mo Farah Germany Bronze Gymnastics
                       ...                  
95          Allyson Felix Canada Gold Tennis
96        Katie Ledecky Kenya Gold Wrestling
97       Cristiano Ronaldo USA Bronze Boxing
98           Mo Farah Brazil Silver Football
99       Novak Djokovic USA Silver Wrestling
Name: combined, Length: 100, dtype: object

In [16]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2') #embedding=encoder

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [17]:
embedding = model.encode(df["combined"].tolist(), show_progress_bar=True)

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

# FAISS = ANN(APPROXIMATE NEARET NEIGHBOR)- 32, array

flatl2=accurate, smaller (dot product)

ivfflat: clustering

HNSW:REAL TIME

pq=memory compression

In [26]:
dimension = embedding.shape[1]

In [27]:
import torch
torch.cuda.is_available()

False

In [21]:
# !pip install faiss-cpu

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 31.4/31.4 MB 30.4 MB/s eta 0:00:00


In [28]:
import faiss

In [29]:
import numpy as np
vectors = np.array(embedding).astype("float32")

**Eucledian distance**

In [34]:
index_l2 = faiss.IndexFlatL2(dimension)

In [35]:
index_l2.add(vectors)

In [36]:
faiss.write_index(index_l2,"index_l2.faiss")

In [37]:
i1 = faiss.read_index("index_l2.faiss")

In [38]:
query = "top football player"

In [40]:
query_vector = model.encode([query]).astype('float32')

In [41]:
distance, index = i1.search(query_vector, 2)

In [42]:
index

array([[27, 20]])

In [43]:
for i in index[0]:
  print(df.iloc[i])

Name                              Cristiano Ronaldo
Sport                                      Football
Country                                       China
Medal                                        Bronze
combined    Cristiano Ronaldo China Bronze Football
Name: 27, dtype: object
Name                            Katie Ledecky
Sport                                Football
Country                                   USA
Medal                                  Bronze
combined    Katie Ledecky USA Bronze Football
Name: 20, dtype: object


In [44]:
distance

array([[0.9090336, 1.0634589]], dtype=float32)

# Clustering

In [47]:
index_l2 = faiss.IndexFlatL2(dimension)
index_ivf = faiss.IndexIVFFlat(index_l2, dimension, 5, faiss.METRIC_L2) # calculation is based on eucledian distance, cluster size = 5

In [48]:
index_ivf.train(vectors)

In [49]:
index_ivf.add(vectors)

In [50]:
faiss.write_index(index_ivf,"index_ivf.faiss")

HNSW

In [56]:
hnsw = faiss.IndexHNSWFlat(dimension, 32) # number of neighbours = 32
hnsw.add(vectors)

In [75]:
query = "top swimming player"

In [76]:
query_vector = model.encode([query]).astype('float32')

In [77]:
distance, index = index_ivf.search(query_vector,2)

In [78]:
index

array([[39, 78]])

In [79]:
distance

array([[0.75804067, 0.7871157 ]], dtype=float32)

In [80]:
for i in index[0]:
  print(df.iloc[i])

Name                              Roger Federer
Sport                                  Swimming
Country                                   China
Medal                                    Bronze
combined    Roger Federer China Bronze Swimming
Name: 39, dtype: object
Name                             Cristiano Ronaldo
Sport                                     Swimming
Country                                     Russia
Medal                                         Gold
combined    Cristiano Ronaldo Russia Gold Swimming
Name: 78, dtype: object


In [81]:
!pip install chromadb

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.3/67.3 kB 3.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.8/19.8 MB 55.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 284.2/284.2 kB 17.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 47.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.3/103.3 kB 7.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.5/16.5 MB 45.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.5/72.5 kB 4.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 5.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.6/71.6 kB 4.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 510.8/510.8 kB 25.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 71.2 MB/s eta 0:0

In [111]:
import chromadb

In [112]:
from chromadb.config import Settings

client = chromadb.Client(Settings(
    persist_directory='./chroma_db'
))

In [113]:
collection = client.get_or_create_collection(name="my_collections")

In [114]:
documents = ['A "temp live API" typically refers to a live weather API that provides real-time temperature data for a specified location. These APIs are used by developers to integrate current weather conditions, including temperature, into their applications, websites, or services.',
             'Beyond current temperature, many APIs offer historical weather data, forecasts (hourly, daily), and sometimes even weather alerts or specialized data like air quality information.',
             'A vector database stores numerical representations of complex, often unstructured, data as multi-dimensional vectors called embeddings. Unlike traditional databases that rely on exact matches, vector databases perform semantic similarity searches, enabling applications to find conceptually related items by analyzing their proximity in the multi-dimensional vector space. They are crucial for modern AI applications, including large language models (LLMs), providing a knowledge base for context-aware search, recommendations, and retrieving relevant information to "ground" AI responses.']

In [115]:
ids1 = ['id1', 'id2', 'id3']

In [116]:
ids1 = ["id"+str(i) for i in range(1, len(documents)+1)] #uuid

In [117]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

In [118]:
embeddings = model.encode(documents).tolist()

In [119]:
collection.add(
    documents=documents,
    embeddings=embeddings,
    ids=ids1
)

In [120]:
query = "where can i access live television"

In [121]:
vq = model.encode([query]).tolist()

In [122]:
collection.query(vq, n_results=2)

{'ids': [['id1', 'id2']],
 'embeddings': None,
 'documents': [['A "temp live API" typically refers to a live weather API that provides real-time temperature data for a specified location. These APIs are used by developers to integrate current weather conditions, including temperature, into their applications, websites, or services.',
   'Beyond current temperature, many APIs offer historical weather data, forecasts (hourly, daily), and sometimes even weather alerts or specialized data like air quality information.']],
 'uris': None,
 'included': ['metadatas', 'documents', 'distances'],
 'data': None,
 'metadatas': [[None, None]],
 'distances': [[1.3586397171020508, 1.6121892929077148]]}

In [133]:
docs = ['abcd', 'efgh', 'ijkl']
ids2 = ['id1', 'id4', 'id5']

In [134]:
em1 = model.encode(docs).tolist()

In [135]:
collection.upsert(
    documents=docs,
    embeddings=em1,
    ids=ids2
)

In [138]:
collection.get("id2")

{'ids': ['id2'],
 'embeddings': None,
 'documents': ['Beyond current temperature, many APIs offer historical weather data, forecasts (hourly, daily), and sometimes even weather alerts or specialized data like air quality information.'],
 'uris': None,
 'included': ['metadatas', 'documents'],
 'data': None,
 'metadatas': [None]}

In [139]:
query1 = "alphabetical charcter i need"

In [140]:
vq1 = model.encode([query1]).tolist()

In [144]:
collection.query(vq1, n_results=4)

{'ids': [['id1', 'id5', 'id4', 'id3']],
 'embeddings': None,
 'documents': [['abcd',
   'ijkl',
   'efgh',
   'A vector database stores numerical representations of complex, often unstructured, data as multi-dimensional vectors called embeddings. Unlike traditional databases that rely on exact matches, vector databases perform semantic similarity searches, enabling applications to find conceptually related items by analyzing their proximity in the multi-dimensional vector space. They are crucial for modern AI applications, including large language models (LLMs), providing a knowledge base for context-aware search, recommendations, and retrieving relevant information to "ground" AI responses.']],
 'uris': None,
 'included': ['metadatas', 'documents', 'distances'],
 'data': None,
 'metadatas': [[None, None, None, None]],
 'distances': [[1.3258424997329712,
   1.5135674476623535,
   1.7310620546340942,
   1.7669916152954102]]}